### ISSUE TITLE
4入力のSumで変換失敗する

### ISSUE THREAD

**Issue by nomaddo** [Idein/nnoir#11]
onnxのmodel zooのもののnnoir変換を試しているのですが、以下のURLのモデルで下のようなエラーが出て終了します。

https://github.com/onnx/models/tree/master/models/semantic_segmentation/DUC

```
[~/Downloads] onnx2nnoir -o model.nnoir ./ResNet101_DUC_HDC.onnx
Traceback (most recent call last):
  File "/home/nomaddo/.pyenv/versions/3.6.8/bin/onnx2nnoir", line 12, in <module>
    ONNX(args.input).to_NNOIR().dump(args.output)
  File "/home/nomaddo/.pyenv/versions/3.6.8/lib/python3.6/site-packages/nnoir_onnx/onnx.py", line 94, in to_NNOIR
    functions = self._to_NNOIR_functions()
  File "/home/nomaddo/.pyenv/versions/3.6.8/lib/python3.6/site-packages/nnoir_onnx/onnx.py", line 168, in _to_NNOIR_functions
    function = op_for_node(generator).to_function(self.nodes, self.constant_nodes)
  File "/home/nomaddo/.pyenv/versions/3.6.8/lib/python3.6/site-packages/nnoir_onnx/operators/sum.py", line 17, in to_function
    raise UnsupportedONNXOperation(self.node, '# of inputs must be 2')
nnoir_onnx.operators.utils.UnsupportedONNXOperation: (input: "fc1_cityscapes_c0"
input: "fc1_cityscapes_c1"
input: "fc1_cityscapes_c2"
input: "fc1_cityscapes_c3"
output: "fc1_cityscapes"
name: "fc1_cityscapes"
op_type: "Sum"
, '# of inputs must be 2') 
```

**Comment by notogawa** [comment]
nnoir-onnxが現状2入力までのSumの実装に留まっているためです．
認識はしてるのと，サポートするオペレータ増やしてく段で対応してくのでこちらとしては閉じます．
(リポジトリ分かれたし)
