### ISSUE TITLE
onnx2nnoir: Support "Mul" 

### ISSUE THREAD

**Issue by nomaddo** [Idein/nnoir#15]
I tried to convert tiny_yolo_v2 in [onnx model zoo](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov2).
Due to the lack of support for "Mul", it was failed as follows:

```
$ onnx2nnoir -o tiny_yolov2.nnoir ~/Downloads/tiny_yolov2/Model.onnx
Traceback (most recent call last):
  File "/home/nomaddo/.local/bin/onnx2nnoir", line 12, in <module>
    ONNX(args.input).to_NNOIR().dump(args.output)
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_onnx/onnx.py", line 47, in __init__
    self.nodes = self._reconstruct_value_info()
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_onnx/onnx.py", line 70, in _reconstruct_value_info
    dfs([], outputs, result)
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_onnx/onnx.py", line 66, in dfs
    dfs(visited, next_nodes, result)
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_onnx/onnx.py", line 66, in dfs
    dfs(visited, next_nodes, result)
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_onnx/onnx.py", line 66, in dfs
    dfs(visited, next_nodes, result)
  [Previous line repeated 29 more times]
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_onnx/onnx.py", line 67, in dfs
    result[n] = op_for_node(generator).get_dummy_output(result)
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_onnx/onnx.py", line 35, in op_for_node
    raise UnsupportedONNXOperation(node, 'converting from {} is undefined'.format(node.op_type))
nnoir_onnx.operators.utils.UnsupportedONNXOperation: (input: "image"
input: "scalerPreprocessor_scale"
output: "scalerPreprocessor_scaled"
name: "Mul"
op_type: "Mul"
domain: ""
, 'converting from Mul is undefined')
```

**Comment by notogawa** [comment]
https://github.com/Idein/nnoir/pull/52 merged.
