### ISSUE TITLE
onnx2nnoir: Support "Sub"

### ISSUE THREAD

**Issue by nomaddo** [Idein/nnoir#21]
"Sub" is required to convert `emotion_ferplus` in onnx model zoo.
https://github.com/onnx/models/tree/master/vision/body_analysis/emotion_ferplus

```
$ onnx2nnoir -o model.nnoir ~/Downloads/emotion_ferplus/model.onnx
Traceback (most recent call last):
  File "./onnx2nnoir", line 12, in <module>
    ONNX(args.input).to_NNOIR().dump(args.output)
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 47, in __init__
    self.nodes = self._reconstruct_value_info()
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 74, in _reconstruct_value_info
    dfs([], outputs, result)
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 70, in dfs
    dfs(visited, next_nodes, result)
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 70, in dfs
    dfs(visited, next_nodes, result)
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 70, in dfs
    dfs(visited, next_nodes, result)
  [Previous line repeated 47 more times]
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 71, in dfs
    result[n] = op_for_node(generator).get_dummy_output(result)
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 35, in op_for_node
    raise UnsupportedONNXOperation(node, 'converting from {} is undefined'.format(node.op_type))
nnoir_onnx.operators.utils.UnsupportedONNXOperation: (input: "Input3"
input: "Constant339"
output: "Minus340_Output_0"
name: "Minus340"
op_type: "Sub"
doc_string: ""
domain: ""
```

**Comment by nomaddo** [comment]
Close via #24
