### ISSUE TITLE
onnx2nnoir: Conversion `resnet18v1.onnx` failed by unexpected error

### ISSUE THREAD

**Issue by nomaddo** [Idein/nnoir#23]
The model comes from the following URL:
https://s3.amazonaws.com/onnx-model-zoo/resnet/resnet18v1/resnet18v1.onnx

in
https://github.com/onnx/models/tree/master/vision/classification/resnet

```
$ ./onnx2nnoir -o /tmp/hoge ~/Downloads/resnet18v1.onnx
2019-08-15 22:34:42.098733956 [E:onnxruntime:InferenceSession, inference_session.cc:470 Initialize] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/nn/batch_norm.h:39 onnxruntime::BatchNorm<T>::BatchNorm(const onnxruntime::OpKernelInfo&) [with T = float] spatial == 1 was false. BatchNormalization kernel for CPU provider does not support non-spatial cases
Stacktrace:

Traceback (most recent call last):
  File "./onnx2nnoir", line 12, in <module>
    ONNX(args.input).to_NNOIR().dump(args.output)
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 46, in __init__
    self.sess = onnxruntime.InferenceSession(path)
  File "/home/nomaddo/.local/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/nn/batch_norm.h:39 onnxruntime::BatchNorm<T>::BatchNorm(const onnxruntime::OpKernelInfo&) [with T = float] spatial == 1 was false. BatchNormalization kernel for CPU provider does not support non-spatial cases
Stacktrace:
```

**Comment by notogawa** [comment]
non-spatial batch normalization is [deprecated and already deleted from OpSet version 8](https://github.com/onnx/onnx/blob/master/docs/Operators.md#batchnormalization). onnxruntime CPU provider does not support non-spatial batch normalization. We follow this onnxruntime behavior.
