### ISSUE TITLE
nnoir-onnx: Cannot translate `pad`

### ISSUE THREAD

**Issue by nomaddo** [Idein/nnoir#46]
[Try the model](https://gist.github.com/nomaddo/0a03f7d83c09dfb99a8be9d69fb6b9ed/raw/2e02757edcd765d79d2cdbf5d5878f4d2af5c071/tmp.onnx)
This onnx model just have one node `Pad`.

```
$ git diff
$ git show HEAD
commit 367bfddb67be6391235d5f4e19a8b798743a65b2 (HEAD -> master, origin/master, origin/HEAD)
Merge: de11afe 943c312
Author: Noriyuki OHKAWA <n.ohkawa@gmail.com>
Date:   Thu Mar 19 16:20:30 2020 +0900

    Merge pull request #44 from Idein/reduce-mem-usage
    
    nnoir-onnx: reduce memory usage (fix #38)
$ onnx2nnoir -o tmp.nnoir /tmp/tmp.onnx 
Traceback (most recent call last):
  File "/home/nomaddo/.local/bin/onnx2nnoir", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/onnx2nnoir", line 12, in <module>
    ONNX(args.input).to_NNOIR().dump(args.output)
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 180, in to_NNOIR
    functions = self._to_NNOIR_functions()
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/onnx.py", line 254, in _to_NNOIR_functions
    function = op_for_node(generator).to_function(self.nodes, self.constant_nodes)
  File "/home/nomaddo/idein/nnoir/nnoir-onnx/nnoir_onnx/operators/pad.py", line 26, in to_function
    n = len(self.pads) // 2
TypeError: object of type 'NoneType' has no len()
```

**Comment by nomaddo** [comment]
This is due to opset version `11`.

**Comment by nomaddo** [comment]
Close via #43
