### ISSUE TITLE
nnoir-chainer: cannot run with `chainer==7.2.0` 

### ISSUE THREAD

**Issue by nomaddo** [Idein/nnoir#55]
`import nnoir_chainer` failed due to the change of chainer interface.

```
[/tmp/work] python3 
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> chainer.__version__
'7.2.0'
>>> import nnoir_chainer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_chainer/__init__.py", line 4, in <module>
    import nnoir_chainer.functions
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_chainer/functions/__init__.py", line 8, in <module>
    import nnoir_chainer.functions.pooling
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_chainer/functions/pooling/__init__.py", line 2, in <module>
    import nnoir_chainer.functions.pooling.max_pooling_2d
  File "/home/nomaddo/.local/lib/python3.7/site-packages/nnoir_chainer/functions/pooling/max_pooling_2d.py", line 1, in <module>
    from chainer.functions.pooling.max_pooling_2d import MaxPooling2D
ModuleNotFoundError: No module named 'chainer.functions.pooling.max_pooling_2d'
```

**Comment by nomaddo** [comment]
Sorry, It seems my mistake
